apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: daws78s
          key: course
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: daws78s
          key: trainer